#!/usr/bin/env bash
#updating packages
sudo apt-get -y update

#installing nginx
sudo apt-get install -y nginx

#creating an index.html file
echo "Hello World!" | sudo tee /var/www/html/index.html

#configuring Nginx to listen to port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

#restarting Nginx
sudo service nginx restart
