#!/usr/bin/env bash
#updating packeges
sudo apt-get update

#install Nginx
sudo apt-get install -y nginx
sudo service nginx start

#allowing firewall
sudo ufw allow 'Nginx HTTP'

#backup default
cp cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#adding contents on the backup
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

#creating a new server block config for redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default



sudo chmod 644 /etc/nginx/sites-available/redirect_me.conf

#new serverblock
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/

#Tesst the Nginx config
sudo nginx -t

#reloading Nginx
sudo service nginx restart
