#!/usr/bin/env bash
#updating packages
#install Nginx
echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
         sudo apt-get install nginx -y

#service start
sudo service nginx start

#allowing firewall
sudo ufw allow 'Nginx HTTP'

#editing permission of files
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

#backup default
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

#adding contents on the backup
echo -e "Hello World!" > /var/www/html/index.nginx-debian.html

#creating a new server block config for redirection
sudo sed -i '24i\       rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#page 404 setup
echo "Ceci n'est pas une page" >> var /var/www/html/error_404.html

sudo sed -i '25i\       error_page 404 /error_404.html;' /etc/nginx/sites-available/default
#reloading Nginx
sudo service nginx restart
