#!/usr/bin/env bash
#a script on what I did in the previous task to allow nginx to listen to port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /run/nginx.pid
