#!/usr/bin/env bash
#printing to infinity and beyond and
#I am invincible when terminated

invincible() {
	echo "I am invincible!!!"
	exit 0
}

trap invincible SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2

done