#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using
# whille loop and if statement

count=1
while [ "$count" -le 10 ]; do
	if [ "$count" -eq 9 ]
	then
		echo "Best School"
		sleep 0.5
		echo "Hi"
	else
		echo "Best School"
	fi
	((count++))
done