#!/usr/bin/env bash
# This script is displaying "Best School" 10 times using
# whille loop and if statement and &&

count=1
while [ "$count" -le 9 ]; do
	if [ "$count" -eq 4 ]
	then
		echo "bad luck"
	fi
	if [ "$count" -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((count++))
done