#!/usr/bin/env bash
# This script displays how a clock works using
# while loop

hour=0

while [ "$hour" -le 12 ]; do
	printf "Hour: %d\n" $hour
	mins=1
	while [ "$mins" -lt 60 ]; do
		printf "%d\n" $mins
		((mins++))
	done
	((hour++))
done