#!/usr/bin/env bash
#updating local host ip and fscebook

#Backing up original host file
cp /etc/hosts ~/hosts.backup

#replacing localhosts
echo "127.0.0.2	localhost" > ~/hosts.backup
echo "8.8.8.8	facebook.com" >> ~ /hosts.backup
cp -f hosts.backup /etc/hosts
