#!/usr/bin/env bash
#updating local host ip and fscebook

#Backing up original host file
cp /etc/hosts ~/hosts.new

#replacing localhosts

echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~ /hosts.new
cp -f ~/hosts.new /etc/hosts
